server:
  port: 9501
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID #防止Cookie冲突，冲突会导致登录验证不通过
oauth2-server-url: http://localhost:9401
spring:
  application:
    name: oauth-client1
security:
  oauth2: #与oauth2-server对应的配置
    client:
      client-id: admin   
      client-secret: admin123456
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize      #这是客户端获取授权码的地址
      access-token-uri: ${oauth2-server-url}/oauth/token               #这是获取令牌的地址
    resource:
      jwt:
        key-uri: ${oauth2-server-url}/oauth/token_key    #oauth/密钥 ，这是解析token内容需要的签名
        
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20002/eureka/